// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbX2/bOBL/KgT3gLsDZDvp9oCDgT6kSbs1Nm2DpM0+tEHBiGOLG4lUyZETX+HvfiAp",
	"WbJFyU42aXa3eWoaksP5P/MbKt9orLJcSZBo6PgbNXECGXM/HsxAov0h1yoHjQLcr2MNDIEfuKWp0hlD",
	"OqacIQxQZEAjiosc6Jga1ELO6DKyRzhIFCz9qFN7rLVD8DVqRSF4iJBBhoXjAmSR0fEnKhUOYiUlxAj2",
	"yDUTKORsMFV6UF9raERBa6VpRGcME7AEB0IKuzgQcg4SlV7QiBb5ANXASkMjalShYxjMlAR60cnORE5V",
	"UKgi57fV1By0EUoGyC0jquFrITRwK7fTT6mONUY2tR01DNZkqb6rlkxd/g4xWj6c7U+0ulm0HSBBzIN2",
	"jOjNQLFcDGLFYQZyADeo2QDZzJ2bs1Q4xY5podPIINNopMJrgckLS9Q4Kd1P90Z/g7hUK6HuSjtjNy/2",
	"9/b26NISbGnuiCEzqDS0FceFuZrwoKtMNcAhy1kscPHLy8YWIRFmoO2ehGl+zTQcxDGkoK0d36o5NDZf",
	"KpUCk3ZzpjiEQy3XClWs0g9uIbABFbJ0GzPYdXoOkiu93YHdavuylipWFKNKf92a2BCu0kLIwV+5bNAy",
	"UQbGsJmTjIOJtcjRhaPfT6rlaItw1b6LZUTfCINqplkWcAiGzP4rEDLTp2fKtGYLZ1chz1laQHi3QchD",
	"K5vsVUTKE5HnJKSnN8oEakC3d+1q/pVRu000kVPNAvUnLQyCNiegbazFIBH0LbXIqyA1awf/oWFKx/Sn",
	"UV0TR2VBHNVxHaCXKIMn6hr0GTL0RBnnwvoOS0/W2O9krhbcUtudMWehDp6skg69vm6pIQl4rfTV7my8",
	"8wdCtHyMl2bruN5uqc3Zt+tNpZ0tTt7YHKC/yVXU4VeVNdr6bFu9obU1Fws7d9VztBxcVH7fp24fHDbg",
	"6gDo239+6LfZE9uNef7WtCN2pRFLICrZDMl2zC59dliX6woW4ZSxkc86MoY9Xm0O3fpWzDSzETcxpghU",
	"X2YMGJOVPW27R1XF2krD7dJKnn4G/baoeVFFdju/uwfahpyBeKtCsV1v5rYfipOgAiTLOvqBstRXLbdB",
	"JjnT3Fdk1OKy8L33inxEC2mKPFfaLoQ653nKZLAVCncJjreQEs8SpuFYyICwqK5Atgu5O0HcIpkqTVgc",
	"gzFCzggmQJpQoN3P+6Z0nd6hyvIUEIhxhD+eHm/tDjxnnl6nULwnQ9wBgnmAtaEKB2/I5Mh2Xdugl2iy",
	"05+Zqo0Npwpe7Baje8BNIWxUEm8aNAyEghZwDAZySAWJ+xTgcfMyuruZHsgYLkHtnmh8Gg/1Bl2ZQskT",
	"DZkwa51OA5Tcp2G7UG2Dh27LHrrDgcCyP05FzBAOEybkH8GJKhMoRRpZmiX4DOptd4qVKiI/l/hi6UWZ",
	"kC/2oxKUumvyCuFudVKPhS1uMMlJcZmK+FdY3IfMxiRfbL1eblqwO5E7kY6FRxs7+WcZpAEH9SsfnVe8",
	"d/7QEcqThwu3Tddt5KHq6qAeVhOujZTpfk+EIYxowEJL4lohV8NilqaGYMKQcCX/idUOhQlo4omboYfH",
	"u4DdA5IUGZMDDYyzyxRIY5moqauUfuTk/ycMsXRdVzIMKVADM0qGLspYnAgJnVddJ4uNC6wOhHQ8fKav",
	"mUgLDZ9pyc+QTEqGvHaEIZDlaGmAdv+VigjpLW6JsTkTqb14SA7IqWOTxCnTYirAECbJmw8fTiphrf+T",
	"y8JqGSwlJGoOWgsOROCwf2AZNGepy1p55L0EoqZj8pmeFa4z+UyJ0k1Jh+StsqLIqRoTN9kaj0YzgcOr",
	"/5qhUNYts0IKXIxiJX13prQZcZhDOjJiNmA6TgRCjIWGkQ9r55xCSTPM+E8mh3jAJB+sxovtrNzy2wpf",
	"tNEM32mYGYqF87en4FPdSw3siqtrGZhGNscrvTh5tbFCkj0g87XSvs+2rrHrvt8EJr8xLYWcmf4z7xT2",
	"k99QUC1kxXqQz61MdXEQ1r4JFMi8OKzGJv0Asm26pZ/gHVZA647n/UTyDoezCjg1bXRPkEs21enTyH2S",
	"V390pJTf23BKs+zOFtgWdTuF3O7xFhoI0fZVUe3VlXgrT2u6rDPDuio7DB/ytVCI5RqMmEnggxJargcb",
	"3ORCg/nCMDCPtmu+hNnW2bUBtpR8PD324HbYBHW9mCMIa080DDxvjqQlb62YKsYrrOwNTLgwsS2DCyIy",
	"NoPh1i4+DHuXrs/yL2mpiEEa5wS+Z6YHOYsTIM+GeyVuHtOq9F1fXw+ZWx4qPRuVZ83oeHL46t3Zq8Gz",
	"4d4wwcwjGYHWt+rZCzlJmZSgycHJpPEkNqaF5DAVErgLvxwkywUd05+He8N96wQME2cjW0BH8/2RQ/98",
	"9M3pfmlXZhAw2y+A9YyBFG7uYOqJBHV3lcmA+/2b0wB7uWYZ+DHpp575hoO/dOyYrYDTeDV9qE2CuoCo",
	"fPkNFesLu9nkSpbA7tnenqsFSmIJh1mepxY1CSVHv5edXk2vt4nfkM75QUAi3hjNLCP6/B5Z8E9BgYtf",
	"Mk5O4WsBfsD+fO/5w9/5TuFrVUjndv/5HkJObNsmWUrOQM9Bk2pjRD2++1S+gtML+7uVu7vflY1tChgA",
	"Ef73hJFYpSnEVUNfndz09CO3/Wy1+nAe57vagCre/+rNvP/wWv8oWYGJ0uJ/8Aimhm4bR+G8ZYF5p+ns",
	"Ym243uzkIIlKyXXCEKy72ULCYcqK1KLWXGkkJlFFysklEMY5cILK7dJgihSrnPa1AJcLy6QmZJwWHL6U",
	"pGggna3mUA+bz+o5xpOHdXhYXr4pbwzS3UyOsNLNWl7m18+qRe0T80vFF/dsvHI4uDG7skVy2XKc/Xu+",
	"O6RUzw9/vLL3I3tru+aNvgm+7Ct8R1Xh63DkZqXbli8nR6t5W7U/0NK5qWV3P7dlvvkd8mFfLvxBPPr5",
	"3s8Pf+lrpS8F5yD/vv1qfeEt2hcLu1wQ5RCLqQDeFZsWbz0F5lNgPgXmQ/V+RSA8/UvdqmKSqVZZY0wy",
	"FWk7Uv2ZP1uwPlRPuvaWuVNn+j0yxYEk788P/NzvKWc85YzvO3xyjfjIO9/4G02ABb5xegOMu8ivHXUz",
	"k9gtk3KlP43wx6v5PSV6l/DYyZ23u99Wd7mteb1Ftli3eh3pbe1W9iVzwcrP8Dp6u6PyIcNv6p+m+4Lk",
	"LPXX6u/W35ZCOc29FK1edX7YTP78kTDLNtfXc1TKf663U9N0uSBFXr3PMUlOzz/Y8657IlxoiDFdBNoo",
	"e+TU3/XaN1p/8l4qK1IUOdM4smQG1R/R1NTXX1Fd99jS3ocE1jX0r1c3MaT/br6aXgrJQl8Cb7xnugvC",
	"D5r326R1fr219fucQHNhZfb+YtGw/9ZoWqTp4qmRe2rkHqORc8/gO8xV4UYYrN/NUyGv/If8W+atq78U",
	"+NtPdjofOM9qjXklP0X+U+R/v8jf8vKnNJkB3j6+/fH3uvpW5scI8pWk/XFe/pmEVa4G1ALmP9hL4lOc",
	"P0qFT4ClmHSidr9M4gTiq9BAJnVhuNsgpMFCeeuF4984Rn30+08GR3R5sfx/AAAA//8ZUKyT8kQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
